### ISSUE TITLE
Comments on straw man functional model of a deformation model.

### ISSUE THREAD

**Issue by ccrook** [opengeospatial/CRS-Deformation-Models#16]
Chris Crook's straw man functional model is at https://github.com/opengeospatial/CRS-Deformation-Models/blob/master/functional-model/strawman-cc/functional-model-strawman-cc.adoc.

This issue is for discussion of this proposal.  For other than minor comments please create a new issue and reference it with a comment in this issue so that ensuing discussion is easy to follow.

**Comment by kevinmkelly** [comment]
This is a great effort by Chris to create a near complete draft DMFM. It will certainly serve to guide the DWG in refining subsequent DMFM drafts, leading to a final robust and implementable DMFM.

My comments on this strawman DMFM are [here.](https://github.com/opengeospatial/CRS-Deformation-Models/issues/17) It was difficult to know how to comment, so in my first go through I commented as if this was the first draft of what would eventually form the final DMFM, even though this may not be the case. Therefore, some of my comments are broad scope and some are minutia. 

This and any subsequent proposed DMFM should include one or more flow diagrams (e.g. [UML](https://www.uml.org/), [ISO 9001 Flowchart Basics](https://the9000store.com/articles/iso-9000-tips-iso-9001-flowchart-basics/)), illustrating the entire workflow together with all decision branch points. If the final standard will include certain formulas and algorithms, as this strawman does, then it must be complete and include all applicable formulas and algorithms, or at the very least reference those that are not given but are recommended. To illustrate correct application of formulas, the document should be peppered with step-by-step numerical examples illustrating how each equation is implemented. This will greatly assist in the process of designing an encoding for the DMFM and specifying the various workflows. 

This draft strawman DMFM is difficult to read and comprehend clearly. Terminology is often inconsistent, and explanations are in some cases confusing or unclear. But "par for the course" for an initial vanguard effort by Chris Crook!

**Comment by ccrook** [comment]
@kevinmkelly Thanks so much for your detailed reivew of the strawman.  One of the shortcomings of the asciidoc format is that we don't have an easy way to comment on it  this is great!  I was vacillating between using adoc and reverting to a google doc which is much easier to comment on. It will take me a while to go through all your comment...

**Comment by rstanaway** [comment]
The postseismic decay part of the functional model could be represented by composite logarithmic and exponential decay functions (e.g. logarithmic + logarithmic + exponential, logarithmic + exponential + exponential, or other combinations). For very large earthquakes such as the Tohoku 2011 earthquake, the use of a single exponential decay model is not adequate to model  significant and ongoing postseismic displacements. It would be good to have scope for several parameters to better model postseismic decay in the functional model. Start and end epochs for the velocity model component would also be useful. It's a good straw man so far. Better than my impersonation with the Covid coiffure!

**Comment by rstanaway** [comment]
Is this also a good time to discuss how the functional model approach may differ with different types of kinematic reference systems? Chris Crook's straw man is tailored for what might be considered a crust-fixed reference system (used very effectively in New Zealand). In this system, the coordinates do not change during the interseismic period (except for readjustments and refinements). Coordinates are only updated for earthquake events (as reverse patches). It does mean that in a plate boundary zone, strain in the coordinate system accumulates during the interseismic period. Other systems would include a plate-fixed reference system where there is theoretically no interseismic strain in a dimensionally stable rotating plate defined by a plate motion model (PMM) using Euler's theorem. Or, the fully kinematic approach where both interseismic motion and seismic displacements form the working CRS (much like ITRF2014).

**Comment by rstanaway** [comment]
Another point of discussion is the use of the terms "epoch", "reference epoch", and "observation epoch". With ITRF realisations, the coordinates of the frame and their uncertainties are defined at the reference epoch, with associated velocities and uncertainties. As ITRF evolves with different realisations, the uncertainties are to some extent reset for each realisation. In the case of crust-fixed reference frames such as NZGD2000 there's an interesting discussion about what exactly is a "reference epoch" in the context of a crust-fixed frame. From my understanding, NZGD2000 and its associated deformation model are monitored within ITRF and every now and then re-adjusted based on the current version of ITRF. The network adjustment is done in a strain free ITRF system close to the "observation epoch" at the time of the adjustment. In NZ's case, this is potentially 20+ years since the crust-fixed RF was realised. As patches are applied to NZGD2000 for seismic displacement updates, the usage of "reference epoch" can become misleading in the sense that the frame as realised in 2000.0 is not the same as the frame defined by the latest version. This of course impacts on how the velocity model is used for NZGD2000 to ITRFyy transformations at other (later) epochs and how uncertainties are estimated using standard error propagation. Since, 2000 the ITRF connection and velocity models have become more refined. So, the uncertainty should realistically be estimated from the observation epoch to another epoch. If 2000.0 is used in the time function of the DMFM, what should we call it (2000.0 that is)?  Also, it seems unrealistic to propagate the uncertainty back to 2000.0 in the case of NZGD2000. 

CC - moved to issue https://github.com/opengeospatial/CRS-Deformation-Models/issues/19

**Comment by ccrook** [comment]
> The postseismic decay part of the functional model could be represented by composite logarithmic and exponential decay functions (e.g. logarithmic + logarithmic + exponential, logarithmic + exponential + exponential, or other combinations)....

This discussion is moved to #18

**Comment by ccrook** [comment]
@rstanaway  comments:

>  Start and end epochs for the velocity model component would also be useful.

Agreed,  The model as a whole has a temporal extent defined but could be useful to determine quickly if a time function is non-zero at a specific epoch.  I didn't include this in the deformation model as generally the time functions are simple enough that it is very quick to determine.

**Comment by ccrook** [comment]
@rstanaway comments:

> Chris Crook's straw man is tailored for what might be considered a crust-fixed reference system (used very effectively in New Zealand).  ... . Other systems would include a plate-fixed reference system where there is theoretically no interseismic strain in a dimensionally stable rotating plate defined by a plate motion model (PMM) using Euler's theorem. Or, the fully kinematic approach where both interseismic motion and seismic displacements form the working CRS (much like ITRF2014).

I think the straw man covers all these cases.  

 - A plate-fixed reference system is just one in which there is no ongoing velocity component.  
 - A fully kinematic approach is one in which the model is applied as a point motion model rather than as a time dependent transformation function

**Comment by kevinmkelly** [comment]
Richard, you have introduced a new "concept" that needs a clear distinction and definition. What is a "crust-fixed reference system" and how does it differ from a "plate-fixed reference system"?

**Comment by ccrook** [comment]
Crust fixed is a nod to New Zealand I think.  NZGD2000 is a "crust fixed", or maybe "plates fixed" or "ground fixed" reference system.  It is not a plate fixed reference system, in that it is not based on a rotation of a rigid plate.

**Comment by kevinmkelly** [comment]
This sounds like an important distinction that has not yet been discussed at our open meetings. Can we put a rigorous definition to "crust-based reference system"? Or, pulling the pieces apart, define and distinguish "plate-fixed" and "crust-fixed". If we will be tossing these terms around, we should have an agreed upon understanding of what they mean.

**Comment by rstanaway** [comment]
Kevin, I agree that the distinction between the different types of reference systems should be clarified. We are all familiar with the "Earth-fixed" concept as that is the basis for ITRF and other similar global reference frames. Point trajectories in these frames are of course non-zero, even on stable plates. 

**Plate-fixed reference system**
The next step in the hierarchy would be a "plate-fixed" reference system where the "Earth-fixed" trajectory is transformed to a stable plate system ideally using a plate motion model (PMM). For the stable portion of the plate the interseismic (secular) component of the trajectory would be zero or close to zero. Of course as one approaches the plate boundary, the secular velocity in a plate-fixed system would trend away from zero due to strain in the plate boundary deformation zone. In the GIA affected areas or where there is some intraplate deformation, plate-fixed velocities would also be non-zero. The advantage of the plate-fixed system is that velocities are minimised for most parts of the plate and any residual velocity differences would highlight other geodynamic processes or localised (non-tectonic related) deformation at play.  I believe this is what the ETRF uses. 

**Crust-fixed reference system**
Logically then, the next step down would be the "crust-fixed" reference system where the coordinates of locally stable geodetic monuments do not change with time (except for episodic deformation events) even within deforming zones. The trajectory would show zero or near-zero interseismic motion, even near a locked plate-bounding fault zone. Of course there comes a point where the strain within the crust-fixed system may reach a point where surveying and positioning tolerance requirements of users of the system is exceeded, thus requiring a reset at a later epoch. NZGD2000 is a text-book example of a crust-fixed reference system used in practice for almost 20 years. Velocity grids in a crust-fixed system could be either defined in terms of ITRF or a dominant plate system within the geographical coverage of the crust-fixed system. In the case of New Zealand there isn't a dominant plate as it's almost entirely within the plate boundary zone between the Australian and Pacific plates, so their model is based on ITRF velocities (ITRF96 to be exact). The distinction between "crust" and "ground surface" is important. The crust is inferred as deeply seated crustal bedrock which underlies the ground surface. Movement of the ground surface (broadly classed as regolith or artificial structures) relative to underlying bedrock is the _bête noire_ of geodetic analysis, as that is where much of the Earth's geodetic infrastructure sits.

**Ground-fixed reference system**
Then I suppose you have what could be termed a "ground-fixed" reference system that is fixed to any surface, regolith or otherwise. Movement of the ground surface is implicitly zero even when it is evidently not if monitored correctly (e.g. urban geodetic networks in a sedimentary basin setting). Cadastral surveys, BIM and civil projects invariably use a ground-fixed system for small areas of coverage where localised deformation is consistent.

Any comments on this hierarchy (the straw dog being led by the straw man as it were) are welcome.

**Comment by kevinmkelly** [comment]
Thanks very much, Richard. This distinction turns out to be somewhat critical to how we generalize a DMFM to any of these systems, if indeed it can be generalized. It also makes us aware of the underlying premise of the NZDM, which may or may not apply to other regions. On another note, in the crust-fixed system, how are locally stable points determined? To what stable reference are they compared? If it is to ITRF station velocities, then these are station specific which may themselves be located in deforming zones. I am now somewhat confused on how crust-fixed systems (like in NZ) operate and perform. But I may be alone in that confusion!!

**Comment by rstanaway** [comment]
Hi Kevin, yes you are quite right. Local stability is really based on repeat site tie measurements from a local fiducial monitoring network and maybe also redundant collocated CORS. The assumption is that sites within a given nearby radius will have the same interseismic velocity (in fact that is a constraint in the ITRF realisation). In the absence of local monitoring networks, a bedrock fixed site is not normally expected to show localised displacement provided that the site is near level.

**Comment by ndonnelly** [comment]
Even after working on it for 15+ years, I still get confused by New Zealand's datum, so you are definitely not alone, Kevin! It is fair to say our own understanding of NZGD2000 has evolved significantly in the last 10 years.

The reference to "locally-stable" marks in the context of a country located totally in a deforming zone is probably best understood as being true ONLY in the context of a local reference frame (ie NZGD2000) defined to be crust-fixed (implemented with a deformation model). Due to the use of the deformation model, there are many marks in New Zealand that have a trajectory of (approximately) zero when calculated in terms of NZGD2000.

We currently define NZGD2000 in terms of the global network of IGS station coordinates and velocities (transformed to ITRF96 where necessary). That is the stable reference to which our deformation model and CORS etc are aligned. So it is the stability of the global frame as a whole, rather then individual stations in the global network, which is the critical factor. Global stations may come in or out of our implementation of NZGD2000 as new versions of the global frame are promulgated, or as stations are affected by regional or local deformation.

**Comment by ccrook** [comment]
@kevinmkelly  notes: (on plate-fixed vs ground/whatever fixed)

> This distinction turns out to be somewhat critical to how we generalize a DMFM to any of these systems, if indeed it can be generalized

I'm not sure it makes much difference at all to the deformation model functional model.  As per comment [above](https://github.com/opengeospatial/CRS-Deformation-Models/issues/16#issuecomment-712520519) I think it relates to implementation/work flow/metadata.  

Essentially if the deformation model is used to define a ground fixed reference system as in NZ then it is being used as a time dependent coordinate transformation.  If it is being used to transform coordinates in time to a reference epoch on a plate fixed reference frame then it is being used as a point motion model.  

In practice there isn't really that much difference between these two cases - the location of a point in plate fixed reference frame at a reference epoch is (in the same way as NZGD2000) only accessible using the deformation model (except at some reference stations arguably).

**Comment by rstanaway** [comment]
Yes, I agree with @ccrook the same DMFM and deformation model can be used in different cases but with different work flows and implementation. That is likely to be a follow on project once the DMFM is ironed out. Maybe I'm looking too much at the end aim. Ultimately all the different types of reference systems and models will be related to some version of ITRF as a realisation of the time invariant ITRS. It's important not to lose the chain of traceability as the different systems and frames evolve over time. This is where I think the reference epoch concept is important as that is a tie point for the relationship between different time-dependent reference frames. In some ways it harks back to an older discussion about the distinction between a datum and a frame. 

It's also good that Chris has made the distinction between the time-dependent transformation used with NZGD2000 and a point motion model. NZGD2000 was originally realised as ITRF96@2000.0 with 2000.0 as the reference epoch. Since then there have been a number of updates (seismic patches) and readjustments, including an improved velocity model (ITRF96 based) and forward patch correction models (also ITRF96 based). This results in later "versions" of NZGD2000 having coordinates different from those at the original reference epoch usually reflecting just the seismic displacements. For ITRF96@epoch to NZGD2000 transformations 2000.0 is still used an epoch (or is it now just a parameter or nominal epoch) for the time function using only the velocity model component of the DM. The distinction between that approach and using the DM as point motion model may appear to be trivial, but it depends if the original geometry is to be recovered (which is very rarely required in most practical cases and usually unknown) or something resembling the current geometry including only the interseismic strain from the original epoch. THAT is a lot more useful from a practical perspective. Hence, I agree with @ccrook regarding the propagation of uncertainty being made only from the epoch of readjustment not from the original realisation epoch.

**Comment by kevinmkelly** [comment]
Thank you Nic, Richard and Chris for your detailed explanations. Please forgive my silence while I try and wrap my head around all this. One important take-away stated by @ccrook is that, if designed well, the DMFM can be applied in any of the aforementioned reference systems.

On another note, though not relevant to the DMFM, is that any reference frame or datum that implements a DMFM is tied to that model to realize the datum. It is almost, though not exactly, as if the DMFM is the datum. This is not different from ITRF in that its realization is also dependent on numerous geophysical and geodynamic models.

**Comment by rstanaway** [comment]
**Grid boundary discontinuity**
Hi Chris @ccrook , This morning's discussion was very useful indeed. The problem with obtaining values outside a grid is not uncommon, but treating "no data" as zero does present problems in many cases. For example, I've used some geoid packages which give zero for N values for input positions outside the model grid or polygon of validity- which of course is not correct. The way I see it is that there are two types of grids. (1) Where values are zero around the boundary and values outside the grid are implicitly also zero (such as a correction model) and (2) where there is no valid data outside the grid, so that if a position outside the grid is used, it should come up with a flag and not be zero. For denser subgrids within parent grids the interpolation along the subgrid boundary should also match that of the parent grid to avoid model discontinuities infinitesimally either side of the subgrid boundary. For PNG use, I have generated subgrid grid boundary values by interpolating the parent grid along the subgrid boundary to avoid this, but there may be better approaches out there. If the deformation model has a boundary, input values outside it should not generate a solution as it maybe used in error.

**Comment by ccrook** [comment]
> The problem with obtaining values outside a grid is not uncommon, but treating "no data" as zero does present problems in many cases

This is continued in #26

**Comment by ccrook** [comment]
This issue has some fantastic discussion.  I am closing it as I think the pertinent points have now either been incorporated into the strawman document or moved to more specific issues.  

However the discussion above with regard to different types of reference systems (plates,earth,ground fixed) is not covered elsewhere.  This should possibly be included in the glossary @rstanaway
