### ISSUE TITLE
Does the DM need to support displacements in angular units

### ISSUE THREAD

**Issue by ccrook** [opengeospatial/CRS-Deformation-Models#44]
Currently I believe all deformation models in use define a displacement in terms of metres (or an equivalent linear unit).  

The deformation model specification also allows for deformation expressed in angular measure (eg seconds of latitude, longitude).   Is this a useful feature or could the model and specification be simplified by removing this capability.   

It was included as a supported capability in the feature matrix.

The potential benefit from using angular displacements is that it is numerically more efficient to use - the calculation to convert from metres to degrees removed.

**Comment by busstoptaktik** [comment]
In the static case, the [NTv2](https://web.archive.org/web/20140127204822/http://www.mgs.gov.on.ca/stdprodconsume/groups/content/@mgs/@iandit/documents/resourcelist/stel02_047447.pdf) datum shift format (originally developed for NAD27 -> NAD83 transformations, but now widely used globally) is based on angular displacements.

**Comment by ccrook** [comment]
Yes - NTv2 is definitely using angular displacements.  Does that mean the deformation model needs to?  We have ruled static displacements out of scope for the deformation model.  On the other hand the NTv2 usage does suggest that there may be a desire to use angular displacements in the future.

**Comment by maccraymer** [comment]
The units for NTv2 shifts are defined in the header records so, strictly speaking, the angular units are not cast in stone even though the vast majority of NTv2 grid shift files use seconds.

And our velocity model, based on an extended 3D version of the NTv2 format, uses linear units for velocities (mm/yr).

-Mike

Sent from my iPhone with autocorrect typos

On Oct 11, 2021, at 3:42 PM, Chris Crook ***@***.***> wrote:

﻿

Yes - NTv2 is definitely using angular displacements. Does that mean the deformation model needs to? We have ruled static displacements out of scope for the deformation model. On the other hand the NTv2 usage does suggest that there may be a desire to use angular displacements in the future.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopengeospatial%2FCRS-Deformation-Models%2Fissues%2F44%23issuecomment-940391177&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7Cb449b3cdf5ea4343dfa908d98cef42f2%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637695781517571561%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BsyAQtk8t%2FnyrtprFB0FD6a3cyB4deDalM3XtsL6DZA%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGURRKM2NGIOMONUDP6CYILUGM4WXANCNFSM5FYZTB5Q&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7Cb449b3cdf5ea4343dfa908d98cef42f2%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637695781517581560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EhUXo1DVgMD0Hag7jtyG5Zai75m7G4PFdAgIxxMXyY0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7Cb449b3cdf5ea4343dfa908d98cef42f2%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637695781517591548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PbuWqyGQgKrY0CInuVqRGqHmd5ujspcxwOC9%2B3aQ8SI%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7Cb449b3cdf5ea4343dfa908d98cef42f2%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637695781517591548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=a%2BOtBRkg00vJ5rdWmgxuoNHhCTz5rHbaVmL4xMNmzgo%3D&reserved=0>.

**Comment by busstoptaktik** [comment]
> And our velocity model, based on an extended 3D version of the NTv2 format, uses linear units for velocities (mm/yr).

Which is definitely also the sensible thing to do in this domain. My comment was mostly a matter of "remember to explain this", because the expectation from a newcomer might be to find angular velocities.

**Comment by ccrook** [comment]
@busstoptaktik Good point - thank you

**Comment by ccrook** [comment]
General agreement there is no need to support angular units of displacement.  Displacements will be in linear units, eg m, mm, ...
(This is for the spatial model of elements - it does not apply to a potential 14/15 parameter transformation)

**Comment by ccrook** [comment]
... also doesn't work for "very large displacements", and especially near the poles.
