### ISSUE TITLE
What is a more appropriate name to replace "deformation model"

### ISSUE THREAD

**Issue by ccrook** [opengeospatial/CRS-Deformation-Models#6]
Options include:

* deformation model
* point trajectory model
* trajectory prediction model
* point motion model

**Comment by rstanaway** [comment]
"Deformation Model" can be defined as a container term with sub-component displacement models (e.g. velocity models, coseismic displacement models etc.). This is the concept applied in New Zealand. A broad semantic definition of deformation is "change of shape". In other disciplines such as engineering and structural geology the definition is more specific (considering stress and strain). Displacement is a product of deformation considering only the kinematic nature of the change in shape in absolute or relative terms.  In the geodetic case it is displacement with respect to a fundamental and time-invariant TRS. This could include stable plate motion (internally strain free but still a deformation of the Earth's surface). 

I think using terms which conflict with already defined terminology shouldn't be used. PMM is already used as a Plate Motion Model (e.g. as used by ITRF). Trajectory is a very nice way of defining motion, but to my understanding it is used in a more predictive way also considering forces. Motion of points in our context does not include force models (although it could be argued that tidal and other loading displacements are an exception). Also, I think trajectory is a term used more widely in orbital mechanics and ballistics. I think using "prediction" needs to be treated with caution too, as we cannot predict earthquake displacements.

**Comment by demiangomez** [comment]
In my opinion, deformation is not an appropriate word to broadly describe what we are dealing with. As I mentioned today, you may be dealing with a single point or even a region that is undergoing pure plate rotation (e.g. Brazil) where there is no deformation (although it could be argued that this is a special deformation case, where deformation is zero). Displacement model, however, would be appropriate but it fails to capture the concept of "time progression". A displacement is the vector joining location A with B, but we are dealing with a collection of displacements. In other words, a time series or, as I proposed, a trajectory, which implies a collection of displacements w.r.t a reference position.

According to the Merriam Webster, trajectory is "the curve that a body (such as a planet or comet in its orbit or a rocket) describes in space" or "a path, progression, or line of development resembling a physical trajectory" (see [here](https://www.merriam-webster.com/dictionary/trajectory)). So I'm not convinced that trajectory implies that forces are being studied of considered. Also, the fact that it is often applied to a body doesn't eliminate the possibility of applying it to a particle (which is our case).

As far as I know, the term applied to geodetic time series was introduced by Mike Bevis (see [here](https://link.springer.com/article/10.1007/s00190-013-0685-5)) but maybe someone did it before. His point was to introduce a more generic term that takes into account effects beyond linear velocities. He discusses "trajectory models for reference frames"  using continuous GNSS stations. In my paper about the crustal motion model for Argentina, I introduced the concept of predicting what the trajectory would be at a point without continuous monitoring. Therefore, "trajectory model" is the model of a GNSS station's time series and "trajectory prediction model" (TPM) is the model that "predicts" or interpolates the motions on points where there are no direct observations. Of course this doesn't imply that you are predicting earthquake displacements, which is impossible, but rather predicting both in space and time what the evolution of a station's coordinate would be. Maybe prediction can be changed to "interpolation", but I chose prediction following the least squares collocation terminology which uses this word.

**Comment by rstanaway** [comment]
Hi Demian,
It's a great discussion! One day, I hope to meet you in person. Anyway, it's great to have your input. Yes, I agree that "trajectory model" is an elegant way of describing and predicting point motions and I'm a great advocate of Mike Bevis' extensive research in this area. It's very hard to find a term that accurately encapsulates what we are describing without delving into neologisms. I also agree that stable plate motion is a special case of zero deformation (theoretical strain rate of zero within the plate). At what stage though do we consider strain between two points on adjacent stable plates to be not classified as deformation of the Earth's surface? Sure, the strain is concentrated within the plate boundary zone. My main reservation with using the term "trajectory" is purely a semantic one as it implies something thrown (from its Latin etymology) or in orbit. Anyway, do you have a link to your own research that you can share? That would be of great interest to many of us.

**Comment by kbevers** [comment]
> I think using terms which conflict with already defined terminology shouldn't be used. 

I very much agree with this.

> Also, I think trajectory is a term used more widely in orbital mechanics and ballistics. 

I immediately think about ballistics when I hear the word "trajectory". With that in mind I think of a trajectory as something moving along "simple" path, e.g. linear og parabolic path. That is not always the case for what we are aiming to model here (seismic events etc). 

> I think using "prediction" needs to be treated with caution too, as we cannot predict earthquake displacements.

Agreed. Elastic deformation near glacier fronts is another case that is hard to predict in advance.

To some extent I think this discussion is difficult without a common understanding of what types of deformation (for lack of a better word) we want to model. I would suggest we get that straight to start with. Here's some candidates from the top of my head:

* coseismic deformation
* postseismic deformation
* post-glacial rebound
* elastic deformation
* ... (add yours here)

Similarly a list of phenomena that should not be included in these types of model could be made. I would argue that tectonic plate motions should be on that list.

**Comment by kevinmkelly** [comment]
The previous comments make excellent points. Culling from those, I agree that terms that are well-known in other disciplines or which connote concepts other than what we are doing should be avoided as much as possible. This may exclude terms like "trajectory" and "deformation".  "Prediction" is a real no-go, especially when our work has something to do with earthquakes! Also, prediction is often used along with "trajectory" and some simplification of a force model in Kalman filtering applications. Now, let's not be too hard on ourselves; just because a term connotes other concepts doesn't mean we can't use it, we should just try to avoid it if we can use a descriptor that captures our work and avoids those other terms. In this vain I suggest we use what to me is quite generic, yet an accurate descriptor of what we are modeling: "**Point Motion Model**". This terminology dovetails well with the current ISO 19111 CRS standatd which uses the term "point motion operation" The logic is that a "point motion operation" derives from a "point motion model". Perhaps we can live with the overlap between common abbreviations for our  "point motion model" (PMM) and "plate motion model" (PMM)? Or will that overlap disqualify "point motion model" out of hand?

**Comment by rstanaway** [comment]
Good Morning Kevin. The fact that PMM has already been coined is a nuisance, as I'm struggling to find a better term for what we currently think of as a deformation or point trajectory model. I guess the main issue logically is that there could be duplication of model names for different but similar things which is potentially risky (think of truncated drop down menus in positioning devices). For example, you could have a defined plate motion model (e.g. Australian ITRF2014 PMM) and also an Australian ITRF2014 PMM (point motion model). While they are quite similar and do similar things, the plate motion model would not include sub models of episodic displacements (patches) that would be included in a point motion model. Another straw bale naming possibility is an "Intraframe or coordinate propagation model " which propagates coordinates within a kinematic frame as a function of time. But I'm also mindful of avoiding semantic pitfalls with the correct definition of propagation (e.g. with physics and horticulture - growing coordinates). Maybe there's some good wordsmiths out there to think of a better term!

**Comment by demiangomez** [comment]
Hi Richard,
Indeed, this is a great discussion and it's what we need to find the terminology that captures everything we need. I apologize I forgot to add my own work to yesterday's comment. Here is the link to [Journal of Geodesy](https://link.springer.com/article/10.1007/s00190-015-0871-8). I also hope to meet you in person sometime in the future!

@kbevers : I'm not convinced we need to list of the models / phenomena that we are including or excluding. I think that the definition should be generic enough to accept any type of deformation or displacement, even those that we are not thinking of now but my be significant in the future. Tectonic plate motions are the only signals you see in some places (at least in the horizontal) so I'm not sure why we would leave those out.

@kevinmkelly : I agree that the term "prediction" is probably not the best and the word "model" is already communicating that we are dealing with a mathematical / kinematic description of a station's behavior. The issue is that, for most cases, we have the model of a model! In other words, you have a GNSS trajectory (or motion) model and based on that model we compute yet another model to find the behavior in between stations. I think that Point Motion Model may be a good candidate that captures everything we have on hand. What if added the word "interpolation"? **Point Motion Interpolation Model** (PMIM). That would solve the acronym issue too.

**Comment by kevinmkelly** [comment]
@rstanaway : Agree Richard, two different PMM's will be confusing!

@demiangomez : Good one Demian, we're honing in! How about: **Point Motion Displacement Model** (PMDM), or using the same acronym, but **Point Motion and Displacement Model** (PMDM). The issue with "interpolation" is that our model(s) may not always be interpolated.

**Comment by JATarrio** [comment]
Hi all:
The discussion is certainly at an interesting point. I am going to contribute my point of view to the discussion:

-  I think it is important to indicate that, in addition to the trajectory from a semantic point of view may have differences, the way in which Professor Bevis defines the frames is different in small ways from that of the ITRF; whether we agree or not is a point of divergence that it happens.

-  I think that including the word _point_ greatly limits what the model intends to do, since although it is true that it starts from point positions of points, it is no less true that in the end the change in a surface will be modeled, not always interpolated as @kevinmkelly  says.

- I would remove the word _displacement_, because displacement implies the start and end point, not what exists in between, however motion describes the complete change in a way.


In that sense, I think we should name the model (I think there is consensus in calling it a model), with a surname that indicates time and positioning, since that is the basis of the WG, therefore I think we should name it:

**Time-dependent Motion Model (TDMM)**, which is something that is already used in a similar way at the NGS, that is, nothing new.

The above would imply in a more subjective way (I hate it) to objectively combine what we are going to do.

Regards

**Comment by RogerLott** [comment]
Whatever we call the model, we are modelling a change of coordinates with time. Introducing 'coordinate' into the term/acronym would imply both a point and a field of points. Time-dependent coordinate model?

**Comment by ccrook** [comment]
Couple of thoughts.  

Point motion model:  This feels good to me as it fits with the existing terminology of point motion operation.  However it may also be used (as in the NZ case) as a coordinate transformation, which is a different thing.  Also as noted above it could be misleading in that the model applies for any point on a surface, whereas point motion model carries an implication of the motion of a single point.

Time-dependent coordinate model: Conceptually it is not the coordinate that is time dependent, it is the position of a point fixed on the earth's surface that is time dependent.  The coordinate is not time dependent, it is just a different coordinate at different times.  Possibly a fine distinction!  I do like that it does strongly identify the area of application, which is in coordinate operations.

How about "surface motion model".   It is a model of the motion of objects fixed to the surface of the earth, it is modelled for a surface (ie based on the 2d coordinates defining horizontal location).   I think it is a good description of what it is, though it is maybe not specific enough and doesn't give the connection to the application for coordinate operations.

**Comment by JATarrio** [comment]
>  Time-dependent coordinate model: Conceptually it is not the coordinate that is time dependent, it is the position of a point fixed on the earth's surface that is time dependent. The coordinate is not time dependent, it is just a different coordinate at different times. Possibly a fine distinction! I do like that it does strongly identify the area of application, which is in coordinate operations.
> 
According to this argument, with which I agree, the previous definition would therefore fit:
 Time-dependent Motion Model (TDMM)
Or its variant that the NGS already uses:
 Time-dependent Positioning Model 
The previous one would not seem adequate to me because it leaves out technologies (i.e. INSAR), with which the movement can be quantified, as it is more focused on GNSS.
> How about "surface motion model". It is a model of the motion of objects fixed to the surface of the earth, it is modelled for a surface (ie based on the 2d coordinates defining horizontal location). I think it is a good description of what it is, though it is maybe not specific enough and doesn't give the connection to the application for coordinate operations.
>
We have to be careful, that term is used in geology for mass displacement analysis, and I think it could cause confusion.

**Comment by ccrook** [comment]
@JATarrio - I did think surface model might be used elsewhere.  Geology is possibly close enough to our discipline to be confusing.  Thanks for identifying this

**Comment by ccrook** [comment]
Edited comments on this topic from messaging during the 10 Aug 2020 online meeting:  These notes are from the chat so represent only ideas in formation and may not be in any way a final viewpoint of those commenting.  They have been slightly edited for typos, and comments for which context is unclear have been removed:

Chris Pearson: It is really a displacement model isn't it?

Richard Stanaway: The idea of deformation in our context was "change of shape of the Earth's surface".

Chris Pearson: New Zealand LINZ has models for landslides don't they

Nic Donnelly: Chris P, not in the official model, but yes, LINZ has some wide-area landslide models that could be incorporated in the future

Martin Lidberg: Yes, and we may consider the deformation model to describe the deformation in time of our "static" reference frame, but it may also be "time evolution" of a dynamic/kinematic reference frame. And then it is rather a "velocity model" than a "deformation model".

Richard Stanaway: To my mind "deformation" combines both secular velocities and episodic displacements.

Wan Anom Wan Aris: deformation model associated coordinate trajectories comprises of velocity model (rigid plate motion), coordinate shift (due to co-seismic) and logarithmic/exponential amplitudes (post-seismic slip).

Martin Lidberg: Agree Richard, both "land uplift" and EQs.

Kevin Kelly: That is how I understand it as well. Also, I think the defomation model should be restricted to displacements "within" a particular reference frame and not shifts between different reference frames.

Richard Stanaway: Trajectory/dynamic implies force/acceleration

Richard Stanaway: displacement/kinematic does not consider forces or accelarations.

Richard Stanaway: Displacement model

Phillip McFarland: Deformation is the correct term:

Phillip McFarland: In physics, deformation is the continuum mechanics transformation of a body from a reference configuration to a current configuration

Richard Stanaway: But deformation model is widely used and understood as a displacement model.

Richard Stanaway: Point vs body

Richard Stanaway: If we use trajectory would we need to consider force?

Martin Lidberg: I think "deformation model" still is a candidate for what we call it!

Richard Stanaway: I would stick with displacement model, as that is what we are looking at.

Richard Stanaway: Point motion is also good.

Martin Lidberg: Yes, point motion model is also OK with me.

José Antonio Tarrío: Perhaps the displacement or trajectory model fits better with the terminology, because deformation implies being able to return to the original shape, something that will not happen

Dana Caccamise (NOAA's NGS): I suggest adding the word    at the end ... "surface"    to say ... surface ground deformation.

**Comment by pmcfarla** [comment]
Hi all-

I'm new to this group so I felt hesitant to interject in the conversation yesterday but I want to say here that **I think that deformation model is absolutely the correct term** for what is being discussed. Take for example what @ccrook wrote above:
"It is a model of the motion of objects fixed to the surface of the earth"
Yes! The Earth is a deforming body in space. The lithosphere moves over the asthenosphere, faults slip and cause displacement of points fixed to Earth's crust, glaciers melt and the surface rebounds, etc. all of these phenomena are examples of how the Earth deforms. In continuum mechanics, which is where the geophysicists took the term, deformation is roughly defined as the difference in shape of a body from one configuration to another. It is **not defined in terms of spatial gradients of displacement**. That is the deformation gradient tensor. 
My understanding of the models we are discussing is that the objective is to describe how points fixed to the surface of the Earth change position from one time to another. It is precisely because the changes in position are a function of position at a reference epoch that we are discussing deformation. The position at the reference epoch is a description of the reference state of the deforming body, in this case the Earth. We do not need to be discussing the changes in position for all points on Earth simultaneously for it to be deformation. Simply describing the change in position of a single point affixed to a deforming body as that body deforms from one configuration to another is invoking a deformation model. It is admittedly a limited model of the deformation of the body, but it is a deformation model none the less.

Above, @demiangomez said:
"you may be dealing with a single point or even a region that is undergoing pure plate rotation (e.g. Brazil) where there is no deformation"
This statement depends entirely on which reference frame you are working in. If you are working in the ITRF then plate rotations are absolutely deformation. If you are working in a plate-fixed frame then the motion of the plate is rigid body motion. But, if you are working in a plate fixed frame, you have no need to describe the motion of the plate because your frame is moving with it! 

I apologize if I have stuck my nose in where it doesn't belong but I just wanted to express my opinion. I think the name is technically correct as it stands and it is a name that folks working across various fields are already familiar with. 

Best,
Phillip McFarland

**Comment by kbevers** [comment]
@demiangomez 

> I'm not convinced we need to list of the models / phenomena that we are including or excluding. I think that the definition should be generic enough to accept any type of deformation or displacement, even those that we are not thinking of now but my be significant in the future. Tectonic plate motions are the only signals you see in some places (at least in the horizontal) so I'm not sure why we would leave those out.

I guess this depends on the scope of the work we are undertaking here. If the "deformation model" (or whatever the name) is strictly a gridded (or triangulated?) model, then I would argue that you are better of using a Helmert transformation for the plate motion. If the scope is wider than that, and the model is effectively a concatenated operation consisting of several steps of various types of operations, sure, it makes sense to include tectonic plate motion. It is not clear to me what the scope exactly is, but so far I have assumed the former since mechanisms are already in place to handle stuff like plate motion (and combine it with other coordinate operations).

**Comment by demiangomez** [comment]
@kbevers : Maybe I have some misconception, but I believe that we want to create a model that given an external coordinate in a TRF epoch X will transform it to epoch Y. If our scope is to just deal with deformation (from a geophysical point of view) then users will have to deal with rigid plate motions outside of the model definition we are discussing here. That means that we are providing a partial solution to go from epoch X to Y, at least in ITRF. Or am I missing something?

@pmcfarla : Does it really matter which type of reference frame are we in? That will depend on the user and application. Counties are moving away from plate fixed frames (at least in the SIRGAS region) and in some cases defining a plate fixed frame is difficult (e.g. Antarctica).

In many regions there is a transition from plate rotation into active plate boundary deformation. This is the case in Argentina, where we use ITRF and the eastern side follows the South American plate rotation model. But as you move west deformation increases significantly. If we don't provide a model that deals with the whole spectrum of trajectories / displacements / motions, then users might have a hard time using the model.

**Comment by pmcfarla** [comment]
@demiangomez 
Hey Demian! I hope all is well with you. I was just responding to your example. You gave the example of Brazil which we think of as stable non-deforming craton. I was simply pointing out that we only think of this region as non-deforming when we're standing on it. From the perspective of an Earth-centered Earth-fixed frame and thinking of the Earth as a whole, motion of the Brazilian craton is indeed deformation of the Earth. The fact that neighboring points in the plates interior are not moving with respect to one another does not negate the fact that those points are moving with respect to the ITRF and therefore deforming the Earth when viewed holistically.

**Comment by rstanaway** [comment]
The main benefit of using the term "deformation model" is that the general concept is now widely understood in both the geophysics and geodetic communities (and by extension the wider community who will use these models). The only technical reservation I see from this discussion is its use in stable plate settings where intraplate deformation is theoretically zero. Realistically though there is no such thing as a totally rigid plate as even the most stable plates have co and postseismic deformation from large plate boundary earthquakes (refer to Corne Kreemer and Paul Tregoning's studies on this). Stable plates also have widespread deformations arising from seasonal loading and hydrology changes. The term is currently used in New Zealand to describe a suite of various sub models (velocities, and earthquake displacement patches) to describe positional changes as a function of time in New Zealand. Across the Tasman Sea, Australia is developing an Australian deformation model (referenced to the stable Australian plate) for use in the Australian Terrestrial Reference Frame (ATRF), which is basically a local clone of ITRF. In Papua New Guinea, a nationwide deformation model has been in development for some time (held up by budgetary constraints). The Australian and PNG approaches are likely to follow the New Zealand template. There is the EUREF WG for Deformation Models and there are a number of other countries already using the term to describe point motions in their national reference frames (Japan, Taiwan, Malaysia, Indonesia, Greece to name a few). What I'm saying here in absolutely no way diminishes the use of other terms already used in other research or jurisdictions, but I'm a great believer in the use of plain English and the need to minimise acronyms wherever possible.

**Comment by ElmarBrockmann** [comment]
I very much like the notes to the current version "CRS Deformation models". Tiny change proposal for second item: "Mathematically deformation can be derived from it as the derivative of displacement with respect to position" -> "... with respect to time".

Some futher notes:
- CRS in the current naming - well established in Geodesy, Coordinate + Reference is fine, problematic might be S for System. F for Frame might be more correct as the coordinates represent the system. Better not opening this pandorra box and better remove "CRS" in the naming as it is another abbreviation which might need explanation.
- Just "Coordinate motion model" or "Reference Coordinate motion model" might better show the application in Geodesy
- definetly, @ccrook proposal "Surface motion model" is shorter, more general and should be added to candidates of names (even it might imply that the entire surface is modeled, which the model probably cannot hold)

**Comment by ElmarBrockmann** [comment]
Just a reply to my recently send tiny text modification proposal. 
"with respect to position" is correct. The time dependence, I missed, is implicitly given in the displacement.
So, just leave it short as it is - more explanations makes it not better.

**Comment by pmcfarla** [comment]
@ElmarBrockmann:
Actually, the text as it stand is incorrect. The gradient of the displacement field yields the [deformation gradient tensor](https://www.continuummechanics.org/deformationgradient.html). Not the deformation.

**Comment by ccrook** [comment]
@ElmarBrockmann CRS is just the name of the repository, which is because it is under the auspices of the CRS domain working group of OGC.   This just identifies the repository within the opengeospatial organisational repositories.  

The main thing is to come to a decision on whether we want to adopt another term for "deformation model".  This is generating some good debate!

**Comment by ElmarBrockmann** [comment]
@ccrook Thanks, Chris. Obviously a quite good location under CRS domain. I simply tried with the propsal "Coordinate motion model" or "Reference Coordinate motion model" to bring something in the name which may stand also for its own.
Fruitfull discussion, indeed.

**Comment by ccrook** [comment]
Roger: No clear consensus and multiple ideas make unlikely to come to a consensus on anything other than deformation so why not leave that?

No disagreement with deferring this for another forum.
